[package]
name = "dmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
dungeon-mark = { path = "../dungeon-mark" }
clap = "4.0"
